require 'erb'

task :default => [:legacy, :generate]
task :ng => [:new, :copy_stylesheets, :generate]
task :generate => [:render_pages, :copy_images, :copy_javascripts ]

task :legacy do
  OUTPUT_DIR = "../../website"
  POSTFIX = ""
end

task :new do
  OUTPUT_DIR = "../../../website"
  POSTFIX = "_ng"
end

task :copy_images do
  mkdir_p File.join(OUTPUT_DIR, "images")
  cp Dir["images/*.png"], File.join(OUTPUT_DIR, "images")
  cp Dir["diagrams/*.png"], OUTPUT_DIR
end

task :copy_stylesheets do
  mkdir_p File.join(OUTPUT_DIR, "stylesheets")
  cp Dir["stylesheets/*"], File.join(OUTPUT_DIR, "stylesheets")
end

task :copy_javascripts do
  mkdir_p File.join(OUTPUT_DIR, "javascripts")
  cp Dir["javascripts/*"], File.join(OUTPUT_DIR, "javascripts")
end

task :render_pages do
  mkdir_p OUTPUT_DIR

  cp "index.html", OUTPUT_DIR
  home_layout = IO.readlines("home_layout#{POSTFIX}.html").join(" ")
  standard_layout = IO.readlines("layout#{POSTFIX}.html").join(" ")
  document_layout = IO.readlines("document_layout#{POSTFIX}.html").join(" ")
  render_page('index', "Welcome", home_layout)
  render_page('get_started', "Get Started!", standard_layout)
  render_page('run_the_demo', "Run the Demo", document_layout)
  render_page('how_it_works', "How it Works", document_layout)
  render_page('give_feedback', "We Love Your Feedback!", standard_layout)
  render_page('participate', "Participate!", standard_layout)
  render_page('hack', "Hack the Grid!", standard_layout)
end

def render_page(page, title, layout)
  raw_content = IO.readlines("#{page}.html").join("")
  version = "0.9.2"
  content = ERB.new(raw_content).result(binding)
  template = ERB.new(layout)
  html = template.result(binding)
  File.new("#{OUTPUT_DIR}/#{page}.html", "w+").write(html)
end

