#
# Required : sudo gem install amazon-ec2 
#
# http://groups.google.com/group/ec2-on-rails-discuss/browse_thread/thread/48825d5a0abf9647/e20c2f506dafc435?lnk=gst&q=ssh+capistrano#e20c2f506dafc435
#
require File.dirname(__FILE__) + '/lib/selenium_grid/aws/ec2'

set :ami, ENV["AMI"] || "ami-6801e401"
set :keypair, ENV["EC2_KEYPAIR"]
set :keypair_name, ENV["EC2_KEYPAIR_NAME"] || "grid-keypair"
set :remote_control_port_range, "5555-5555"

set :selenium_grid_path, "/usr/local/lib/selenium-grid-0.9.4"
set :grid, SeleniumGrid::AWS::Cloud.load
set :ec2_client, Class.new.extend(::SeleniumGrid::AWS::Ec2Client)
 
namespace :hub do

  desc "Boot a new EC2 Instance to Run Selenium Grid Hub."
  task :boot do
    SeleniumGrid::AWS::Cloud.update do |cloud|
      puts "Starting a new EC2 Instance..."
      cloud.hub = SeleniumGrid::AWS::Server.boot_and_acquire_dns ami, :keypair => keypair_name
      puts "Started new Hub at #{cloud.hub.public_dns}"
    end
    set :grid, SeleniumGrid::AWS::Cloud.load
    ec2_client.authorize_port 22
    ec2_client.authorize_port 4444
  end

  desc "Start Selenium Grid Hub."
  task :start do
    grid.hub.run "cd #{selenium_grid_path}; nohup rake hub:start BACKGROUND=true", :keypair => keypair    
  end

  desc("Stop Selenium Grid Hub.")
  task :stop do
    grid.hub.run 'cd #{selenium_grid_path}; rake hub:stop', :keypair => keypair
  end

  desc "Open Selenium Grid Hub Console in a browser."
  task :console do
    launcher = PLATFORM["darwin"] ? "open" : "firefox "
    system "open #{grid.hub.console_url}"
  end

  desc "View Selenium Grid Hub logs."
  task :logs do
    launcher = PLATFORM["darwin"] ? "open" : "firefox "
    grid.hub.run 'tail -200f #{selenium_grid_path}/log/hub.log', :keypair => keypair
  end
  
  task :refresh_status do
    SeleniumGrid::AWS::Cloud.update do |cloud|
      cloud.hub.refresh_status
    end
  end
  
end

namespace :rc do

  desc "Boot a new EC2 Instance to run a collection of Selenium Grid Remote Controls."
  task :boot do
    SeleniumGrid::AWS::Cloud.update do |cloud|
      puts "Starting a new EC2 Instance..."
      new_farm = SeleniumGrid::AWS::Server.boot_and_acquire_dns ami, :keypair => keypair_name
      cloud.farms << new_farm
      puts "Started new Remote Control farm at #{new_farm.public_dns}"
    end
    set :grid, SeleniumGrid::AWS::Cloud.load
    ec2_client.authorize_port 22
    ec2_client.authorize_port 5555
  end
  
  desc "Start Remote Controls for all farms."
  task :start do
    grid.farms.each do |farm|
      farm.run "cd #{selenium_grid_path}; nohup rake rc:start_all HUB_URL=#{grid.hub.private_url} HOST=#{farm.private_dns} PORTS=#{remote_control_port_range} BACKGROUND=true", 
               :keypair => keypair
    end
  end

  desc "Stop Remote Controls for all farms."
  task :stop do
    grid.farms.each do |farm|
      farm.run "cd #{selenium_grid_path}; rake rc:stop_all PORTS=#{remote_control_port_range}", 
               :keypair => keypair
    end
  end
  
end


namespace :ec2 do
    
  desc "Check EC2 related configuration."
  task :check_settings do
    %w(EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_KEYPAIR).each do |variable|
      raise <<-EOS unless ENV[variable]
      
        +++++++++++++++++++++++++++++++++++++++++++++++
        You must set #{variable}. 
        
        Read http://docs.amazonwebservices.com/AWSEC2/2007-08-29/GettingStartedGuide/?ref=get-started 
        for more details.
          
        ++++++++++++++++++++++++++++++++++++++++++++++++
      EOS

    end
  end
  
end
